package xerr

// 成功返回
const OK uint32 = 200

/**(前3位代表业务，后3位代表具体功能)**/

// 全局错误码
const (
	SERVER_COMMOM_ERROR uint32 = 100001 + iota
	REQUEST_PARAM_ERROR
	TOKEN_EXPIRE_ERROR
	TOKEN_GENERATE_ERROR
	DB_ERROR
	DB_UPDATE_AFFECTED_ZERO_ERROR
	DB_ERROR_NOT_FOUND
	DB_TRANSACTION_ERROR
)

// 用户模块
const (
	DB_INSERT_USER_SPONSOR_ERROR uint32 = 200001 + iota
	DB_UPDATE_USER_SPONSOR_ERROR
	DB_DELETE_USER_SPONSOR_ERROR
	DB_GET_USER_SPONSOR_LIST_ERROR
	DB_GET_USERS_INFO_ERROR
	DB_USER_AUTH_FIND_ONE_BY_USER_ID_ERROR
)
