package xerr

// 成功返回
const OK uint32 = 200

/**(前3位代表业务，后3位代表具体功能)**/

// 全局错误码
const (
	SERVER_COMMOM_ERROR uint32 = 100001 + iota
	REQUEST_PARAM_ERROR
	TOKEN_EXPIRE_ERROR
	TOKEN_GENERATE_ERROR
	DB_ERROR
	DB_UPDATE_AFFECTED_ZERO_ERROR
	DB_ERROR_NOT_FOUND
	DB_TRANSACTION_ERROR
)

// 用户模块
const (
	DB_INSERT_USER_SPONSOR_ERROR uint32 = 200001 + iota
	DB_UPDATE_USER_SPONSOR_ERROR
	DB_DELETE_USER_SPONSOR_ERROR
	DB_GET_USER_SPONSOR_LIST_ERROR
	DB_GET_USERS_INFO_ERROR
	DB_USER_AUTH_FIND_ONE_BY_USER_ID_ERROR
)

// 抽奖模块
const (
	// 抽奖列表
	DB_GETLASTID_ERROR uint32 = 500001 + iota
	DB_GET_LOTTERY_LIST_ERROR
	DB_GET_WIN_LOTTERY_LIST_ERROR
	DB_GET_PRIZE_LIST_ERROR
	DB_GET_PRIZE_ERROR
	DB_GET_USER_WIN_LOTTERY_LIST_ERROR
	DB_GET_ALL_USER_LOTTERY_LIST_ERROR
	DB_GET_USER_CREATED_LOTTERY_LIST_ERROR
	DB_GET_PARTICIPATED_BY_LOTTERY_ID
	DB_GET_PARTICIPATIONS_COUNT
	DB_GET_CREATED_COUNT_BY_USER_ID
	DB_GET_WON_COUNT_BY_USER_ID
	DB_GET_PARTICIPATION_COUNT_BY_USER_ID
	DB_GET_PRIZE_BY_BY_LOTTERY_ID
	DB_CHECK_IS_PARTICIPATED
	DB_PARTICIPATE_LOTTERY
	DB_GET_PARTICIPATORS_ERROR
	DB_GET_PENDING_LOTTERY_LIST_FAIL
	DB_GET_PARTICIPATORS_COUNT_FAIL
	DB_ANNOUNCE_LOTTERY_FAIL
	ANNOUNCE_LOTTERY_FAIL
	DB_UPDATE_STATUS_ERROR
	DB_UPDATE_WINNER_ERROR
	DB_FIND_PARTICIPATION_BY_LOTTERY_ID_AND_USER_ID_ERR
	DB_FIND_LOTTERY_BY_ID_ERR
	DB_FIND_PRIZES_BY_LOTTERY_ID_ERR
	DB_DECR_PRIZE_STOCK_ERR
)
