services:
  nginx-gateway:
    image: nginx:1.27.3
    container_name: go-lottery-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - go-lottery-network
    depends_on:
      - go-lottery

  go-lottery:
    build:
      context: .
      dockerfile: deploy/modd/Dockerfile
    dns:
      - 8.8.8.8
      - 223.5.5.5  # 阿里公共DNS
    container_name: go-lottery
    environment:
      - TZ=Asia/Shanghai
      - GOPROXY=https://goproxy.cn,direct
    env_file:
      - ./.env
    working_dir: /go/go-lottery
    volumes:
      - .:/go/go-lottery
      - ./data/go-lottery/go:/go/go-lottery/log
    privileged: true
    restart: always
    networks:
      - go-lottery-network


networks:
  go-lottery-network:
    name: go-lottery-network
    external: true