global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

# 这里表示抓取对象的配置
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s #重写了全局抓取间隔时间，由15秒重写成5秒
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'checkin-rpc'
    static_configs:
      - targets: [ 'go-lottery:3001' ]
        labels:
          job: checkin-rpc
          app: checkin-rpc
          env: dev
  - job_name: 'checkin-api'
    static_configs:
      - targets: [ 'go-lottery:3002' ]
        labels:
          job: checkin-api
          app: checkin-api
          env: dev
  - job_name: 'comment-rpc'
    static_configs:
      - targets: [ 'go-lottery:3003' ]
        labels:
          job: comment-rpc
          app: comment-rpc
          env: dev
  - job_name: 'comment-api'
    static_configs:
      - targets: [ 'go-lottery:3004' ]
        labels:
          job: comment-api
          app: comment-api
          env: dev
  - job_name: 'lottery-rpc'
    static_configs:
      - targets: [ 'go-lottery:3005' ]
        labels:
          job: lottery-rpc
          app: lottery-rpc
          env: dev
  - job_name: 'lottery-api'
    static_configs:
      - targets: [ 'go-lottery:3006' ]
        labels:
          job: lottery-api
          app: lottery-api
          env: dev
  - job_name: 'notice-rpc'
    static_configs:
      - targets: [ 'go-lottery:3007' ]
        labels:
          job: notice-rpc
          app: notice-rpc
          env: dev
  - job_name: 'notice-api'
    static_configs:
      - targets: [ 'go-lottery:3008' ]
        labels:
          job: notice-api
          app: notice-api
          env: dev
  - job_name: 'upload-rpc'
    static_configs:
      - targets: [ 'go-lottery:3009' ]
        labels:
          job: upload-rpc
          app: upload-rpc
          env: dev
  - job_name: 'upload-api'
    static_configs:
      - targets: [ 'go-lottery:3010' ]
        labels:
          job: upload-api
          app: upload-api
          env: dev
  - job_name: 'usercenter-rpc'
    static_configs:
      - targets: [ 'go-lottery:3011' ]
        labels:
          job: usercenter-rpc
          app: usercenter-rpc
          env: dev
  - job_name: 'usercenter-api'
    static_configs:
      - targets: [ 'go-lottery:3012' ]
        labels:
          job: usercenter-api
          app: usercenter-api
          env: dev