// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryCommentCommentIdPrefix = "cache:goLotteryComment:comment:id:"
)

type (
	commentModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Comment) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Comment) error
		FindOne(ctx context.Context, id int64) (*Comment, error)
		Update(ctx context.Context, tx *gorm.DB, data *Comment) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Comment) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Comment) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultCommentModel struct {
		gormc.CachedConn
		table string
	}

	Comment struct {
		Id          int64     `gorm:"column:id;primary_key"`
		UserId      int64     `gorm:"column:user_id"`      // 用户id
		LotteryId   int64     `gorm:"column:lottery_id"`   // 抽奖id
		PrizeName   string    `gorm:"column:prize_name"`   // 奖品名称
		Content     string    `gorm:"column:content"`      // 晒单评论内容
		Pics        string    `gorm:"column:pics"`         // 晒单评论图片
		PraiseCount int64     `gorm:"column:praise_count"` // 点赞数量
		CreateTime  time.Time `gorm:"column:create_time"`  // 创建时间
		UpdateTime  time.Time `gorm:"column:update_time"`  // 更新时间
	}
)

func (Comment) TableName() string {
	return "`comment`"
}

func newCommentModel(conn *gorm.DB, c cache.CacheConf) *defaultCommentModel {
	return &defaultCommentModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`comment`",
	}
}

func (m *defaultCommentModel) GetCacheKeys(data *Comment) []string {
	if data == nil {
		return []string{}
	}
	goLotteryCommentCommentIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCommentCommentIdPrefix, data.Id)
	cacheKeys := []string{
		goLotteryCommentCommentIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultCommentModel) Insert(ctx context.Context, tx *gorm.DB, data *Comment) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(commentOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultCommentModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Comment) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultCommentModel) FindOne(ctx context.Context, id int64) (*Comment, error) {
	goLotteryCommentCommentIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCommentCommentIdPrefix, id)
	var resp Comment
	err := m.QueryCtx(ctx, &resp, goLotteryCommentCommentIdKey, func(conn *gorm.DB) error {
		return conn.Model(&Comment{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentModel) Update(ctx context.Context, tx *gorm.DB, data *Comment) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(commentOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultCommentModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Comment) error {
	clearData := make([]Comment, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultCommentModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Comment{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultCommentModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Comment) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultCommentModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultCommentModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryCommentCommentIdPrefix, primary)
}

func (m *defaultCommentModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Comment{}).Where("`id` = ?", primary).Take(v).Error
}
