// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryCommentPraiseIdPrefix              = "cache:goLotteryComment:praise:id:"
	cacheGoLotteryCommentPraiseUserIdCommentIdPrefix = "cache:goLotteryComment:praise:userId:commentId:"
)

type (
	praiseModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Praise) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Praise) error
		FindOne(ctx context.Context, id int64) (*Praise, error)
		FindOneByUserIdCommentId(ctx context.Context, userId int64, commentId int64) (*Praise, error)
		Update(ctx context.Context, tx *gorm.DB, data *Praise) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Praise) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Praise) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultPraiseModel struct {
		gormc.CachedConn
		table string
	}

	Praise struct {
		Id         int64     `gorm:"column:id;primary_key"`
		UserId     int64     `gorm:"column:user_id"`     // 点赞用户ID
		CommentId  int64     `gorm:"column:comment_id"`  // 评论ID
		CreateTime time.Time `gorm:"column:create_time"` // 创建时间
		UpdateTime time.Time `gorm:"column:update_time"` // 更新时间
	}
)

func (Praise) TableName() string {
	return "`praise`"
}

func newPraiseModel(conn *gorm.DB, c cache.CacheConf) *defaultPraiseModel {
	return &defaultPraiseModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`praise`",
	}
}

func (m *defaultPraiseModel) GetCacheKeys(data *Praise) []string {
	if data == nil {
		return []string{}
	}
	goLotteryCommentPraiseIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCommentPraiseIdPrefix, data.Id)
	goLotteryCommentPraiseUserIdCommentIdKey := fmt.Sprintf("%s%v:%v", cacheGoLotteryCommentPraiseUserIdCommentIdPrefix, data.UserId, data.CommentId)
	cacheKeys := []string{
		goLotteryCommentPraiseIdKey, goLotteryCommentPraiseUserIdCommentIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultPraiseModel) Insert(ctx context.Context, tx *gorm.DB, data *Praise) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(praiseOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultPraiseModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Praise) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultPraiseModel) FindOne(ctx context.Context, id int64) (*Praise, error) {
	goLotteryCommentPraiseIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCommentPraiseIdPrefix, id)
	var resp Praise
	err := m.QueryCtx(ctx, &resp, goLotteryCommentPraiseIdKey, func(conn *gorm.DB) error {
		return conn.Model(&Praise{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPraiseModel) FindOneByUserIdCommentId(ctx context.Context, userId int64, commentId int64) (*Praise, error) {
	goLotteryCommentPraiseUserIdCommentIdKey := fmt.Sprintf("%s%v:%v", cacheGoLotteryCommentPraiseUserIdCommentIdPrefix, userId, commentId)
	var resp Praise
	err := m.QueryRowIndexCtx(ctx, &resp, goLotteryCommentPraiseUserIdCommentIdKey, m.formatPrimary, func(conn *gorm.DB, v interface{}) (interface{}, error) {
		if err := conn.Model(&Praise{}).Where("`user_id` = ? and `comment_id` = ?", userId, commentId).Take(&resp).Error; err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPraiseModel) Update(ctx context.Context, tx *gorm.DB, data *Praise) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(praiseOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultPraiseModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Praise) error {
	clearData := make([]Praise, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultPraiseModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Praise{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultPraiseModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Praise) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultPraiseModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultPraiseModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryCommentPraiseIdPrefix, primary)
}

func (m *defaultPraiseModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Praise{}).Where("`id` = ?", primary).Take(v).Error
}
