// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryUploadUploadFileIdPrefix = "cache:goLotteryUpload:uploadFile:id:"
)

type (
	uploadFileModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *UploadFile) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []UploadFile) error
		FindOne(ctx context.Context, id int64) (*UploadFile, error)
		Update(ctx context.Context, tx *gorm.DB, data *UploadFile) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []UploadFile) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []UploadFile) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultUploadFileModel struct {
		gormc.CachedConn
		table string
	}

	UploadFile struct {
		Id         int64     `gorm:"column:id;primary_key"`
		UserId     int64     `gorm:"column:user_id"`   // 上传用户id
		FileName   string    `gorm:"column:file_name"` // 文件名
		Ext        string    `gorm:"column:ext"`       // 扩展名
		Size       int64     `gorm:"column:size"`      // 文件大小
		Url        string    `gorm:"column:url"`       // 下载链接
		CreateTime time.Time `gorm:"column:create_time"`
		UpdateTime time.Time `gorm:"column:update_time"`
	}
)

func (UploadFile) TableName() string {
	return "`upload_file`"
}

func newUploadFileModel(conn *gorm.DB, c cache.CacheConf) *defaultUploadFileModel {
	return &defaultUploadFileModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`upload_file`",
	}
}

func (m *defaultUploadFileModel) GetCacheKeys(data *UploadFile) []string {
	if data == nil {
		return []string{}
	}
	goLotteryUploadUploadFileIdKey := fmt.Sprintf("%s%v", cacheGoLotteryUploadUploadFileIdPrefix, data.Id)
	cacheKeys := []string{
		goLotteryUploadUploadFileIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultUploadFileModel) Insert(ctx context.Context, tx *gorm.DB, data *UploadFile) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(uploadFileOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultUploadFileModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []UploadFile) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultUploadFileModel) FindOne(ctx context.Context, id int64) (*UploadFile, error) {
	goLotteryUploadUploadFileIdKey := fmt.Sprintf("%s%v", cacheGoLotteryUploadUploadFileIdPrefix, id)
	var resp UploadFile
	err := m.QueryCtx(ctx, &resp, goLotteryUploadUploadFileIdKey, func(conn *gorm.DB) error {
		return conn.Model(&UploadFile{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUploadFileModel) Update(ctx context.Context, tx *gorm.DB, data *UploadFile) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(uploadFileOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultUploadFileModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []UploadFile) error {
	clearData := make([]UploadFile, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultUploadFileModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&UploadFile{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultUploadFileModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []UploadFile) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultUploadFileModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultUploadFileModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryUploadUploadFileIdPrefix, primary)
}

func (m *defaultUploadFileModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&UploadFile{}).Where("`id` = ?", primary).Take(v).Error
}
