// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	upload "Luckify/app/upload/cmd/api/internal/handler/upload"
	"Luckify/app/upload/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 文件上传
				Method:  http.MethodPost,
				Path:    "/upload/add",
				Handler: upload.UploadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/upload/v1"),
	)
}
