// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ReceiveEventReq struct {
	Signature string `body:"signature"`
	TimeStamp string `body:"timestamp"`
	Nonce     string `body:"nonce"`
}

type ReceiveEventResp struct {
}

type VerifyEventReq struct {
	Signature string `form:"signature"`
	TimeStamp string `form:"timeStamp"`
	Nonce     string `form:"nonce"`
	Echostr   string `form:"echostr"`
}

type VerifyEventResp struct {
}
