// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	checkin "Luckify/app/checkin/cmd/api/internal/handler/checkin"
	"Luckify/app/checkin/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 签到操作
				Method:  http.MethodPost,
				Path:    "/checkin",
				Handler: checkin.CheckinHandler(serverCtx),
			},
			{
				// 领取任务奖励
				Method:  http.MethodPost,
				Path:    "/checkin/claimReward",
				Handler: checkin.ClaimRewardHandler(serverCtx),
			},
			{
				// 获取签到状态以及积分
				Method:  http.MethodPost,
				Path:    "/checkin/getCheckin",
				Handler: checkin.GetCheckinHandler(serverCtx),
			},
			{
				// 获取用户任务完成状态
				Method:  http.MethodPost,
				Path:    "/checkin/getTasks",
				Handler: checkin.GetTasksHandler(serverCtx),
			},
			{
				// 改变任务签到状态
				Method:  http.MethodPost,
				Path:    "/checkin/updateSub",
				Handler: checkin.UpdateSubHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/checkin/v1"),
	)
}
