// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryCheckinTaskProgressIdPrefix = "cache:goLotteryCheckin:taskProgress:id:"
)

type (
	taskProgressModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *TaskProgress) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []TaskProgress) error
		FindOne(ctx context.Context, id int64) (*TaskProgress, error)
		Update(ctx context.Context, tx *gorm.DB, data *TaskProgress) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TaskProgress) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []TaskProgress) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTaskProgressModel struct {
		gormc.CachedConn
		table string
	}

	TaskProgress struct {
		Id                    int64     `gorm:"column:id;primary_key"`
		UserId                int64     `gorm:"column:user_id"`
		IsParticipatedLottery int64     `gorm:"column:is_participated_lottery"`
		IsInitiatedLottery    int64     `gorm:"column:is_initiated_lottery"`
		IsSubCheckin          int64     `gorm:"column:is_sub_checkin"`
		CreateTime            time.Time `gorm:"column:create_time"` // 创建时间
		UpdateTime            time.Time `gorm:"column:update_time"` // 更新时间
	}
)

func (TaskProgress) TableName() string {
	return "`task_progress`"
}

func newTaskProgressModel(conn *gorm.DB, c cache.CacheConf) *defaultTaskProgressModel {
	return &defaultTaskProgressModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`task_progress`",
	}
}

func (m *defaultTaskProgressModel) GetCacheKeys(data *TaskProgress) []string {
	if data == nil {
		return []string{}
	}
	goLotteryCheckinTaskProgressIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskProgressIdPrefix, data.Id)
	cacheKeys := []string{
		goLotteryCheckinTaskProgressIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTaskProgressModel) Insert(ctx context.Context, tx *gorm.DB, data *TaskProgress) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(taskProgressOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultTaskProgressModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []TaskProgress) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultTaskProgressModel) FindOne(ctx context.Context, id int64) (*TaskProgress, error) {
	goLotteryCheckinTaskProgressIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskProgressIdPrefix, id)
	var resp TaskProgress
	err := m.QueryCtx(ctx, &resp, goLotteryCheckinTaskProgressIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&TaskProgress{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskProgressModel) Update(ctx context.Context, tx *gorm.DB, data *TaskProgress) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(taskProgressOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultTaskProgressModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TaskProgress) error {
	clearData := make([]TaskProgress, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultTaskProgressModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&TaskProgress{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultTaskProgressModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []TaskProgress) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultTaskProgressModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTaskProgressModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskProgressIdPrefix, primary)
}

func (m *defaultTaskProgressModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&TaskProgress{}).Where("`id` = ?", primary).Take(v).Error
}
