// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryCheckinTasksIdPrefix = "cache:goLotteryCheckin:tasks:id:"
)

type (
	tasksModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *Tasks) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []Tasks) error
		FindOne(ctx context.Context, id int64) (*Tasks, error)
		Update(ctx context.Context, tx *gorm.DB, data *Tasks) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Tasks) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []Tasks) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTasksModel struct {
		gormc.CachedConn
		table string
	}

	Tasks struct {
		Id         int64     `gorm:"column:id;primary_key"`
		Type       int64     `gorm:"column:type"` // 1 for novice, 2 for daily, 3 for weekly
		Content    string    `gorm:"column:content"`
		Integral   int64     `gorm:"column:integral"` // Increased wish value after completion
		Path       string    `gorm:"column:path"`
		CreateTime time.Time `gorm:"column:create_time"` // 创建时间
		UpdateTime time.Time `gorm:"column:update_time"` // 更新时间
	}
)

func (Tasks) TableName() string {
	return "`tasks`"
}

func newTasksModel(conn *gorm.DB, c cache.CacheConf) *defaultTasksModel {
	return &defaultTasksModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`tasks`",
	}
}

func (m *defaultTasksModel) GetCacheKeys(data *Tasks) []string {
	if data == nil {
		return []string{}
	}
	goLotteryCheckinTasksIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTasksIdPrefix, data.Id)
	cacheKeys := []string{
		goLotteryCheckinTasksIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTasksModel) Insert(ctx context.Context, tx *gorm.DB, data *Tasks) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(tasksOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultTasksModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []Tasks) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultTasksModel) FindOne(ctx context.Context, id int64) (*Tasks, error) {
	goLotteryCheckinTasksIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTasksIdPrefix, id)
	var resp Tasks
	err := m.QueryCtx(ctx, &resp, goLotteryCheckinTasksIdKey, func(conn *gorm.DB) error {
		return conn.Model(&Tasks{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTasksModel) Update(ctx context.Context, tx *gorm.DB, data *Tasks) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(tasksOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultTasksModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []Tasks) error {
	clearData := make([]Tasks, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultTasksModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&Tasks{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultTasksModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []Tasks) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultTasksModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTasksModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryCheckinTasksIdPrefix, primary)
}

func (m *defaultTasksModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&Tasks{}).Where("`id` = ?", primary).Take(v).Error
}
