// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/SpectatorNan/gorm-zero/gormc/batchx"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGoLotteryCheckinTaskRecordIdPrefix = "cache:goLotteryCheckin:taskRecord:id:"
)

type (
	taskRecordModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *TaskRecord) error
		BatchInsert(ctx context.Context, tx *gorm.DB, news []TaskRecord) error
		FindOne(ctx context.Context, id int64) (*TaskRecord, error)
		Update(ctx context.Context, tx *gorm.DB, data *TaskRecord) error
		BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TaskRecord) error
		BatchDelete(ctx context.Context, tx *gorm.DB, datas []TaskRecord) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		// deprecated. recommend add a transaction in service context instead of using this
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultTaskRecordModel struct {
		gormc.CachedConn
		table string
	}

	TaskRecord struct {
		Id         int64     `gorm:"column:id;primary_key"`
		Type       int64     `gorm:"column:type"`
		UserId     int64     `gorm:"column:user_id"`
		TaskId     int64     `gorm:"column:task_id"`
		IsFinished int64     `gorm:"column:is_finished"` // 0 means not completed, 1 means completed
		CreateTime time.Time `gorm:"column:create_time"` // 创建时间
		UpdateTime time.Time `gorm:"column:update_time"` // 更新时间
	}
)

func (TaskRecord) TableName() string {
	return "`task_record`"
}

func newTaskRecordModel(conn *gorm.DB, c cache.CacheConf) *defaultTaskRecordModel {
	return &defaultTaskRecordModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`task_record`",
	}
}

func (m *defaultTaskRecordModel) GetCacheKeys(data *TaskRecord) []string {
	if data == nil {
		return []string{}
	}
	goLotteryCheckinTaskRecordIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskRecordIdPrefix, data.Id)
	cacheKeys := []string{
		goLotteryCheckinTaskRecordIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultTaskRecordModel) Insert(ctx context.Context, tx *gorm.DB, data *TaskRecord) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(taskRecordOmitColumns...).Save(&data).Error
	}, m.GetCacheKeys(data)...)
	return err
}
func (m *defaultTaskRecordModel) BatchInsert(ctx context.Context, tx *gorm.DB, news []TaskRecord) error {

	err := batchx.BatchExecCtx(ctx, m, news, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Create(&news).Error
	})

	return err
}

func (m *defaultTaskRecordModel) FindOne(ctx context.Context, id int64) (*TaskRecord, error) {
	goLotteryCheckinTaskRecordIdKey := fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskRecordIdPrefix, id)
	var resp TaskRecord
	err := m.QueryCtx(ctx, &resp, goLotteryCheckinTaskRecordIdKey, func(conn *gorm.DB) error {
		return conn.Model(&TaskRecord{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTaskRecordModel) Update(ctx context.Context, tx *gorm.DB, data *TaskRecord) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && errors.Is(err, ErrNotFound) {
		return err
	}
	clearKeys := append(m.GetCacheKeys(old), m.GetCacheKeys(data)...)
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Omit(taskRecordOmitColumns...).Save(data).Error
	}, clearKeys...)
	return err
}
func (m *defaultTaskRecordModel) BatchUpdate(ctx context.Context, tx *gorm.DB, olds, news []TaskRecord) error {
	clearData := make([]TaskRecord, 0, len(olds)+len(news))
	clearData = append(clearData, olds...)
	clearData = append(clearData, news...)
	err := batchx.BatchExecCtx(ctx, m, clearData, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&news).Error
	})

	return err
}

func (m *defaultTaskRecordModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&TaskRecord{}, id).Error
	}, m.GetCacheKeys(data)...)
	return err
}

func (m *defaultTaskRecordModel) BatchDelete(ctx context.Context, tx *gorm.DB, datas []TaskRecord) error {
	err := batchx.BatchExecCtx(ctx, m, datas, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&datas).Error
	})

	return err
}

// deprecated. recommend add a transaction in service context instead of using this
func (m *defaultTaskRecordModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultTaskRecordModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGoLotteryCheckinTaskRecordIdPrefix, primary)
}

func (m *defaultTaskRecordModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&TaskRecord{}).Where("`id` = ?", primary).Take(v).Error
}
