// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: app/upload/cmd/rpc/pb/upload.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Ext           string                 `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	FileData      []byte                 `protobuf:"bytes,5,opt,name=fileData,proto3" json:"fileData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadReq) Reset() {
	*x = FileUploadReq{}
	mi := &file_app_upload_cmd_rpc_pb_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadReq) ProtoMessage() {}

func (x *FileUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_cmd_rpc_pb_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadReq.ProtoReflect.Descriptor instead.
func (*FileUploadReq) Descriptor() ([]byte, []int) {
	return file_app_upload_cmd_rpc_pb_upload_proto_rawDescGZIP(), []int{0}
}

func (x *FileUploadReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FileUploadReq) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileUploadReq) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *FileUploadReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadReq) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type FileUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadResp) Reset() {
	*x = FileUploadResp{}
	mi := &file_app_upload_cmd_rpc_pb_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadResp) ProtoMessage() {}

func (x *FileUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_upload_cmd_rpc_pb_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadResp.ProtoReflect.Descriptor instead.
func (*FileUploadResp) Descriptor() ([]byte, []int) {
	return file_app_upload_cmd_rpc_pb_upload_proto_rawDescGZIP(), []int{1}
}

func (x *FileUploadResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_app_upload_cmd_rpc_pb_upload_proto protoreflect.FileDescriptor

const file_app_upload_cmd_rpc_pb_upload_proto_rawDesc = "" +
	"\n" +
	"\"app/upload/cmd/rpc/pb/upload.proto\x12\x02pb\"\x85\x01\n" +
	"\rFileUploadReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x10\n" +
	"\x03ext\x18\x03 \x01(\tR\x03ext\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x1a\n" +
	"\bfileData\x18\x05 \x01(\fR\bfileData\"\"\n" +
	"\x0eFileUploadResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url29\n" +
	"\x06upload\x12/\n" +
	"\x06upload\x12\x11.pb.FileUploadReq\x1a\x12.pb.FileUploadRespB\x06Z\x04./pbb\x06proto3"

var (
	file_app_upload_cmd_rpc_pb_upload_proto_rawDescOnce sync.Once
	file_app_upload_cmd_rpc_pb_upload_proto_rawDescData []byte
)

func file_app_upload_cmd_rpc_pb_upload_proto_rawDescGZIP() []byte {
	file_app_upload_cmd_rpc_pb_upload_proto_rawDescOnce.Do(func() {
		file_app_upload_cmd_rpc_pb_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_upload_cmd_rpc_pb_upload_proto_rawDesc), len(file_app_upload_cmd_rpc_pb_upload_proto_rawDesc)))
	})
	return file_app_upload_cmd_rpc_pb_upload_proto_rawDescData
}

var file_app_upload_cmd_rpc_pb_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_upload_cmd_rpc_pb_upload_proto_goTypes = []any{
	(*FileUploadReq)(nil),  // 0: pb.FileUploadReq
	(*FileUploadResp)(nil), // 1: pb.FileUploadResp
}
var file_app_upload_cmd_rpc_pb_upload_proto_depIdxs = []int32{
	0, // 0: pb.upload.upload:input_type -> pb.FileUploadReq
	1, // 1: pb.upload.upload:output_type -> pb.FileUploadResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_upload_cmd_rpc_pb_upload_proto_init() }
func file_app_upload_cmd_rpc_pb_upload_proto_init() {
	if File_app_upload_cmd_rpc_pb_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_upload_cmd_rpc_pb_upload_proto_rawDesc), len(file_app_upload_cmd_rpc_pb_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_upload_cmd_rpc_pb_upload_proto_goTypes,
		DependencyIndexes: file_app_upload_cmd_rpc_pb_upload_proto_depIdxs,
		MessageInfos:      file_app_upload_cmd_rpc_pb_upload_proto_msgTypes,
	}.Build()
	File_app_upload_cmd_rpc_pb_upload_proto = out.File
	file_app_upload_cmd_rpc_pb_upload_proto_goTypes = nil
	file_app_upload_cmd_rpc_pb_upload_proto_depIdxs = nil
}
